version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/dogu